_wandb:
    value:
        cli_version: 0.21.0
        e:
            uafzw7zry2kuucpccsk1mpumgfolvh12:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 12
                cpu_count_logical: 20
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "1055703064576"
                        used: "280341377024"
                email: umbertofrancesco.carolini@poliba.it
                executable: /home/umberto-francesco-carolini/Desktop/self_balancing_robot_with_DRL/venv/bin/python
                git:
                    commit: 9adfa58d6e8a8af86290e820b6b14f9581bc116b
                    remote: https://github.com/FraPis23/self_balancing_robot_with_DRL.git
                gpu: NVIDIA GeForce RTX 4060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4352
                      memoryTotal: "17175674880"
                      name: NVIDIA GeForce RTX 4060 Ti
                      uuid: GPU-bd55f96f-f274-4815-8d39-a20be590d8a5
                host: icaro
                memory:
                    total: "67227291648"
                os: Linux-6.14.0-27-generic-x86_64-with-glibc2.39
                program: /home/umberto-francesco-carolini/Desktop/self_balancing_robot_with_DRL/train.py
                python: CPython 3.12.2
                root: /home/umberto-francesco-carolini/Desktop/self_balancing_robot_with_DRL
                startedAt: "2025-08-12T09:21:32.833993Z"
                writerId: uafzw7zry2kuucpccsk1mpumgfolvh12
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.12.2
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
file_prefix:
    value: PPO_2025-08-12_11-21-32
folder_prefix:
    value: PPO_2025-08-12_11-21-32
iterations:
    value: 1000000
model:
    value: PPO
policies_folder:
    value: ./policies
processes:
    value: 50
xml_file:
    value: ./models/scene.xml
